const mapping = {
  airplane: '',
  alarm: '',
  alignBottom: '',
  alignTop: '',
  alignStart: '',
  alignEnd: '',
  alignCenter: '',
  alignMiddle: '',
  archive: '',
  arrowCw: 'arrow-clockwise',
  arrowCcw: 'arrow-counterclockwise',
  arrowDown: '',
  arrowUp: '',
  arrowStart: 'arrow-left',
  arrowEnd: 'arrow-right',
  arrowsStartEnd: 'arrow-left-right',
  arrowsRepeat: 'arrow-repeat',
  arrowsCollapse: '',
  arrowsCollapseV: 'arrows-collapse-vertical',
  arrowsExpand: '',
  arrowsExpandV: 'arrows-expand-vertical',
  arrowsSplit: '~',
  arrowsMerge: '~',
  arrowsShuffle: 'shuffle',
  article: 'file-text',
  asterisk: '',
  award: '',
  backspace: '',
  backspaceReverse: '',
  ban: '',
  chartBar: 'bar-chart',
  chartPie: 'pie-chart',
  battery: '',
  bag: '',
  balloon: '',
  bank: 'bank2',
  barcode: 'upc',
  barn: '~',
  barricade: '~',
  baseball: '~',
  basket: '',
  basketball: '~',
  batteryCharging: '',
  batteryEmpty: 'battery',
  batteryFull: '',
  batteryHigh: 'battery-full',
  batteryLow: 'battery-half',
  bed: '~',
  beer: '~',
  bell: '',
  bellRinging: '~',
  bellSlash: '',
  bellZ: '~',
  bicycle: '',
  binary: 'file-binary',
  binoculars: '',
  bird: '~',
  bluetooth: '',
  bluetoothConnected: 'bluetooth',
  bluetoothSlash: 'bluetooth',
  bluetoothOff: 'bluetooth',
  boat: '~',
  bomb: '~',
  book: '',
  bookOpen: 'book',
  bookmark: ''
}

function iconset (ctx) {
  return {
    name: 'bootstrap-icons',
    css: 'waibuBootstrapIcons.virtual:/bsi/font/bootstrap-icons.min.css',
    prefix: 'bi-',
    mapping
  }
}

export default iconset
