const mapping = {
  house: '',
  addressBook: 'person-rolodex',
  airplane: '',
  airplaneTakeoff: '~',
  airplaneLanding: '~',
  airplay: 'cast',
  alarm: '',
  alien: '~',
  alignBottom: '',
  alignTop: '',
  alignStart: '',
  alignEnd: '',
  alignCenter: '',
  alignMiddle: '',
  ambulance: '~',
  anchor: 'link',
  angle: '~',
  aperture: '~',
  archive: '',
  arrowDown: '',
  arrowUp: '',
  arrowStart: 'arrow-left',
  arrowEnd: 'arrow-right',
  arrowCircleDown: 'arrow-down-circle',
  arrowCircleUp: 'arrow-up-circle',
  arrowCircleStart: 'arrow-left-circle',
  arrowCircleEnd: 'arrow-right-circle',
  arrowSquareDown: 'arrow-down-square',
  arrowSquareUp: 'arrow-up-square',
  arrowSquareStart: 'arrow-left-square',
  arrowSquareEnd: 'arrow-right-square',
  arrowFatDown: '~',
  arrowFatUp: '~',
  arrowFatStart: '~',
  arrowFatEnd: '~',
  arrowClockwise: '',
  arrowCounterClockwise: 'arrow-counterclockwise',
  arrowsIn: '~',
  arrowsOut: 'arrows-fullscreen',
  arrowsCollapseHorizontal: 'arrows-collapse-vertical',
  arrowsExpandHorizontal: 'arrows-expand-vertical',
  arrowsCollapseVertical: 'arrows-collapse',
  arrowsExpandVertical: 'arrows-expand',
  arrowsSplit: '~',
  arrowsMerge: '~',
  arrowsShuffle: 'shuffle',
  article: 'file-text',
  asterisk: '',
  at: '~',
  atom: '~',
  axe: '~',
  baby: '~',
  bag: '',
  balloon: '',
  bank: 'bank2',
  barcode: 'upc',
  barn: '~',
  barricade: '~',
  baseball: '~',
  basket: '',
  basketball: '~',
  batteryCharging: '',
  batteryEmpty: 'battery',
  batteryFull: '',
  batteryHigh: 'battery-full',
  batteryLow: 'battery-half',
  bed: '~',
  beer: '~',
  bell: '',
  bellRinging: '~',
  bellSlash: '',
  bellZ: '~',
  bicycle: '',
  binary: 'file-binary',
  binoculars: '',
  bird: '~',
  bluetooth: '',
  bluetoothConnected: 'bluetooth',
  bluetoothSlash: 'bluetooth',
  bluetoothOff: 'bluetooth',
  boat: '~',
  bomb: '~',
  book: '',
  bookOpen: 'book',
  bookmark: ''
}

function iconset (ctx) {
  return {
    name: 'bootstrap-icons',
    css: 'waibuBootstrapIcons.virtual:/bsi/font/bootstrap-icons.min.css',
    prefix: 'bi-',
    mapping
  }
}

export default iconset
